# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianNeuralNetwork, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[ 0.91620641 -0.77279409  0.33048932  0.2640768   0.34484474]
 [ 0.5125053  -0.75169093 -0.87127399 -0.21405076 -0.53944607]
 [-0.0537074   0.10669794 -0.50372155 -0.07859156  0.52321436]
 [-0.19836865  0.98750004 -0.8973727  -0.86936949 -0.90326119]
 [-0.1593579  -0.30111161 -0.59061157 -0.08986537  0.21175906]
 [ 0.22240962 -0.1185493  -0.64476461  0.57617029  0.22601114]
 [ 0.86726502 -0.53260971 -0.19891196 -0.02842786 -0.48005051]
 [ 0.53064069  0.0428547   0.53144329  0.48852445 -0.9971394 ]
 [ 0.26625276 -0.17786302  0.79713303  0.77805245 -0.45259756]
 [ 0.7735104  -0.34739189  0.46862325  0.03816798 -0.38249249]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a1', 'a2', 'a1', 'a2', 'a2', 'a2', 'a2', 'a2', 'a1', 'a2']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [0, 0, 1, 0, 0, 1, 1, 1, 1, 0]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/25 [00:00<?, ?it/s]

SVI:   4%|▍         | 1/25 [00:01<00:24,  1.01s/it]

SVI:   4%|▍         | 1/25 [00:01<00:24,  1.01s/it, loss=2064.4001]

SVI:   8%|▊         | 2/25 [00:01<00:23,  1.01s/it, loss=2553.7463]

SVI:  12%|█▏        | 3/25 [00:01<00:22,  1.01s/it, loss=2639.9485]

SVI:  16%|█▌        | 4/25 [00:01<00:21,  1.01s/it, loss=2549.9548]

SVI:  20%|██        | 5/25 [00:01<00:20,  1.01s/it, loss=2644.0415]

SVI:  24%|██▍       | 6/25 [00:01<00:19,  1.01s/it, loss=2343.3962]

SVI:  28%|██▊       | 7/25 [00:01<00:18,  1.01s/it, loss=3159.5942]

SVI:  32%|███▏      | 8/25 [00:01<00:17,  1.01s/it, loss=2227.9946]

SVI:  36%|███▌      | 9/25 [00:01<00:16,  1.01s/it, loss=2425.1892]

SVI:  40%|████      | 10/25 [00:01<00:15,  1.01s/it, loss=3631.2668]

SVI:  44%|████▍     | 11/25 [00:01<00:14,  1.01s/it, loss=2789.7761]

SVI:  48%|████▊     | 12/25 [00:01<00:13,  1.01s/it, loss=2237.7971]

SVI:  52%|█████▏    | 13/25 [00:01<00:12,  1.01s/it, loss=2084.6411]

SVI:  56%|█████▌    | 14/25 [00:01<00:11,  1.01s/it, loss=2782.4910]

SVI:  60%|██████    | 15/25 [00:01<00:10,  1.01s/it, loss=2422.5056]

SVI:  64%|██████▍   | 16/25 [00:01<00:09,  1.01s/it, loss=2184.8298]

SVI:  68%|██████▊   | 17/25 [00:01<00:08,  1.01s/it, loss=2622.9119]

SVI:  72%|███████▏  | 18/25 [00:01<00:07,  1.01s/it, loss=2384.5527]

SVI:  76%|███████▌  | 19/25 [00:01<00:06,  1.01s/it, loss=2574.4492]

SVI:  80%|████████  | 20/25 [00:01<00:05,  1.01s/it, loss=2392.1492]

SVI:  84%|████████▍ | 21/25 [00:01<00:04,  1.01s/it, loss=1825.0632]

SVI:  88%|████████▊ | 22/25 [00:01<00:03,  1.01s/it, loss=2248.3152]

SVI:  92%|█████████▏| 23/25 [00:01<00:02,  1.01s/it, loss=2496.5952]

SVI:  96%|█████████▌| 24/25 [00:01<00:01,  1.01s/it, loss=3193.9336]

SVI: 100%|██████████| 25/25 [00:01<00:00,  1.01s/it, loss=2318.3813]

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:00<00:29,  1.12it/s]

SVI:   3%|▎         | 1/34 [00:00<00:29,  1.12it/s, loss=3079.8469]

SVI:   6%|▌         | 2/34 [00:00<00:28,  1.12it/s, loss=2670.9294]

SVI:   9%|▉         | 3/34 [00:00<00:27,  1.12it/s, loss=1892.3955]

SVI:  12%|█▏        | 4/34 [00:00<00:26,  1.12it/s, loss=1959.1798]

SVI:  15%|█▍        | 5/34 [00:00<00:25,  1.12it/s, loss=2298.4543]

SVI:  18%|█▊        | 6/34 [00:00<00:24,  1.12it/s, loss=3695.0742]

SVI:  21%|██        | 7/34 [00:00<00:24,  1.12it/s, loss=1885.9630]

SVI:  24%|██▎       | 8/34 [00:00<00:23,  1.12it/s, loss=2542.7793]

SVI:  26%|██▋       | 9/34 [00:00<00:22,  1.12it/s, loss=2033.8470]

SVI:  29%|██▉       | 10/34 [00:00<00:21,  1.12it/s, loss=2638.0696]

SVI:  32%|███▏      | 11/34 [00:00<00:20,  1.12it/s, loss=3256.2185]

SVI:  35%|███▌      | 12/34 [00:00<00:19,  1.12it/s, loss=2099.8340]

SVI:  38%|███▊      | 13/34 [00:00<00:18,  1.12it/s, loss=2548.5745]

SVI:  41%|████      | 14/34 [00:00<00:17,  1.12it/s, loss=2585.9377]

SVI:  44%|████▍     | 15/34 [00:00<00:16,  1.12it/s, loss=3335.5762]

SVI:  47%|████▋     | 16/34 [00:00<00:16,  1.12it/s, loss=2823.6536]

SVI:  50%|█████     | 17/34 [00:00<00:15,  1.12it/s, loss=3159.6143]

SVI:  53%|█████▎    | 18/34 [00:00<00:14,  1.12it/s, loss=2300.0293]

SVI:  56%|█████▌    | 19/34 [00:00<00:13,  1.12it/s, loss=2277.2585]

SVI:  59%|█████▉    | 20/34 [00:00<00:12,  1.12it/s, loss=2989.7273]

SVI:  62%|██████▏   | 21/34 [00:00<00:11,  1.12it/s, loss=1814.6318]

SVI:  65%|██████▍   | 22/34 [00:00<00:10,  1.12it/s, loss=2613.2209]

SVI:  68%|██████▊   | 23/34 [00:00<00:09,  1.12it/s, loss=1859.1849]

SVI:  71%|███████   | 24/34 [00:00<00:08,  1.12it/s, loss=2761.6729]

SVI:  74%|███████▎  | 25/34 [00:00<00:08,  1.12it/s, loss=2094.1599]

SVI:  76%|███████▋  | 26/34 [00:00<00:07,  1.12it/s, loss=2502.7034]

SVI:  79%|███████▉  | 27/34 [00:00<00:06,  1.12it/s, loss=3463.4717]

SVI:  82%|████████▏ | 28/34 [00:00<00:05,  1.12it/s, loss=3077.2996]

SVI:  85%|████████▌ | 29/34 [00:00<00:04,  1.12it/s, loss=2270.4238]

SVI:  88%|████████▊ | 30/34 [00:00<00:03,  1.12it/s, loss=2098.7056]

SVI:  91%|█████████ | 31/34 [00:00<00:02,  1.12it/s, loss=2212.9353]

SVI:  94%|█████████▍| 32/34 [00:00<00:01,  1.12it/s, loss=2397.1221]

SVI:  97%|█████████▋| 33/34 [00:00<00:00,  1.12it/s, loss=3001.5574]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.33it/s, loss=3001.5574]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.33it/s, loss=1813.2456]