# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianNeuralNetwork, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[ 0.52779259 -0.52021294  0.93275245  0.27018602 -0.35368837]
 [ 0.51011815  0.70764127 -0.72245382  0.4809334  -0.06144767]
 [ 0.68626855 -0.28395193 -0.24021974  0.5863586  -0.27472513]
 [-0.47270332  0.0291788   0.46720373  0.09545299  0.7319706 ]
 [-0.01264105 -0.57349908  0.04683035 -0.7284884   0.114381  ]
 [-0.36179268  0.11809081  0.94369624  0.69124152 -0.50602418]
 [-0.9504625   0.54797741 -0.21777088 -0.49821547  0.17482341]
 [ 0.42611563 -0.46954029  0.18983071  0.39988962 -0.16400701]
 [-0.81865513  0.60355821 -0.39569763 -0.81097596 -0.99657086]
 [-0.20586979 -0.5189677  -0.25793693  0.61545501  0.16956291]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a1', 'a1', 'a2', 'a1', 'a1', 'a2', 'a2', 'a1', 'a2', 'a1']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [0, 1, 1, 0, 1, 0, 0, 1, 0, 1]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:01<00:34,  1.05s/it]

SVI:   3%|▎         | 1/34 [00:01<00:34,  1.05s/it, loss=2277.6829]

SVI:   6%|▌         | 2/34 [00:01<00:33,  1.05s/it, loss=3043.4768]

SVI:   9%|▉         | 3/34 [00:01<00:32,  1.05s/it, loss=2506.9392]

SVI:  12%|█▏        | 4/34 [00:01<00:31,  1.05s/it, loss=2405.9324]

SVI:  15%|█▍        | 5/34 [00:01<00:30,  1.05s/it, loss=2363.9363]

SVI:  18%|█▊        | 6/34 [00:01<00:29,  1.05s/it, loss=2032.4479]

SVI:  21%|██        | 7/34 [00:01<00:28,  1.05s/it, loss=2419.6616]

SVI:  24%|██▎       | 8/34 [00:01<00:27,  1.05s/it, loss=2432.9797]

SVI:  26%|██▋       | 9/34 [00:01<00:26,  1.05s/it, loss=3195.0867]

SVI:  29%|██▉       | 10/34 [00:01<00:25,  1.05s/it, loss=2840.8972]

SVI:  32%|███▏      | 11/34 [00:01<00:24,  1.05s/it, loss=2421.7795]

SVI:  35%|███▌      | 12/34 [00:01<00:23,  1.05s/it, loss=1815.8112]

SVI:  38%|███▊      | 13/34 [00:01<00:21,  1.05s/it, loss=2630.8977]

SVI:  41%|████      | 14/34 [00:01<00:20,  1.05s/it, loss=2807.7727]

SVI:  44%|████▍     | 15/34 [00:01<00:19,  1.05s/it, loss=3207.1562]

SVI:  47%|████▋     | 16/34 [00:01<00:18,  1.05s/it, loss=2810.7900]

SVI:  50%|█████     | 17/34 [00:01<00:17,  1.05s/it, loss=2239.4414]

SVI:  53%|█████▎    | 18/34 [00:01<00:16,  1.05s/it, loss=3007.2581]

SVI:  56%|█████▌    | 19/34 [00:01<00:15,  1.05s/it, loss=2202.1262]

SVI:  59%|█████▉    | 20/34 [00:01<00:14,  1.05s/it, loss=2157.4568]

SVI:  62%|██████▏   | 21/34 [00:01<00:13,  1.05s/it, loss=2355.1462]

SVI:  65%|██████▍   | 22/34 [00:01<00:12,  1.05s/it, loss=2324.7991]

SVI:  68%|██████▊   | 23/34 [00:01<00:11,  1.05s/it, loss=2630.7844]

SVI:  71%|███████   | 24/34 [00:01<00:10,  1.05s/it, loss=1667.4349]

SVI:  74%|███████▎  | 25/34 [00:01<00:09,  1.05s/it, loss=2405.5657]

SVI:  76%|███████▋  | 26/34 [00:01<00:08,  1.05s/it, loss=2260.1704]

SVI:  79%|███████▉  | 27/34 [00:01<00:07,  1.05s/it, loss=2586.1741]

SVI:  82%|████████▏ | 28/34 [00:01<00:06,  1.05s/it, loss=1833.3385]

SVI:  85%|████████▌ | 29/34 [00:01<00:05,  1.05s/it, loss=2280.5398]

SVI:  88%|████████▊ | 30/34 [00:01<00:04,  1.05s/it, loss=2416.9631]

SVI:  91%|█████████ | 31/34 [00:01<00:03,  1.05s/it, loss=2413.0901]

SVI:  94%|█████████▍| 32/34 [00:01<00:02,  1.05s/it, loss=3286.1335]

SVI:  97%|█████████▋| 33/34 [00:01<00:01,  1.05s/it, loss=1992.8622]

SVI: 100%|██████████| 34/34 [00:01<00:00, 20.81it/s, loss=1992.8622]

SVI: 100%|██████████| 34/34 [00:01<00:00, 20.81it/s, loss=1614.6421]

SVI:   0%|          | 0/25 [00:00<?, ?it/s]

SVI:   4%|▍         | 1/25 [00:00<00:21,  1.10it/s]

SVI:   4%|▍         | 1/25 [00:00<00:21,  1.10it/s, loss=1778.8550]

SVI:   8%|▊         | 2/25 [00:00<00:20,  1.10it/s, loss=2373.2417]

SVI:  12%|█▏        | 3/25 [00:00<00:19,  1.10it/s, loss=2787.5439]

SVI:  16%|█▌        | 4/25 [00:00<00:19,  1.10it/s, loss=1856.0391]

SVI:  20%|██        | 5/25 [00:00<00:18,  1.10it/s, loss=2396.9768]

SVI:  24%|██▍       | 6/25 [00:00<00:17,  1.10it/s, loss=2189.4429]

SVI:  28%|██▊       | 7/25 [00:00<00:16,  1.10it/s, loss=2588.5474]

SVI:  32%|███▏      | 8/25 [00:00<00:15,  1.10it/s, loss=2113.2317]

SVI:  36%|███▌      | 9/25 [00:00<00:14,  1.10it/s, loss=2086.9646]

SVI:  40%|████      | 10/25 [00:00<00:13,  1.10it/s, loss=2012.2039]

SVI:  44%|████▍     | 11/25 [00:00<00:12,  1.10it/s, loss=2269.8372]

SVI:  48%|████▊     | 12/25 [00:00<00:11,  1.10it/s, loss=2735.0647]

SVI:  52%|█████▏    | 13/25 [00:00<00:10,  1.10it/s, loss=3101.3926]

SVI:  56%|█████▌    | 14/25 [00:00<00:09,  1.10it/s, loss=2341.4263]

SVI:  60%|██████    | 15/25 [00:00<00:09,  1.10it/s, loss=3055.8481]

SVI:  64%|██████▍   | 16/25 [00:00<00:08,  1.10it/s, loss=2422.2815]

SVI:  68%|██████▊   | 17/25 [00:00<00:07,  1.10it/s, loss=2216.8406]

SVI:  72%|███████▏  | 18/25 [00:00<00:06,  1.10it/s, loss=2594.2568]

SVI:  76%|███████▌  | 19/25 [00:00<00:05,  1.10it/s, loss=2618.4778]

SVI:  80%|████████  | 20/25 [00:00<00:04,  1.10it/s, loss=2319.5449]

SVI:  84%|████████▍ | 21/25 [00:00<00:03,  1.10it/s, loss=2195.4858]

SVI:  88%|████████▊ | 22/25 [00:00<00:02,  1.10it/s, loss=2448.6912]

SVI:  92%|█████████▏| 23/25 [00:00<00:01,  1.10it/s, loss=2247.8999]

SVI:  96%|█████████▌| 24/25 [00:00<00:00,  1.10it/s, loss=2145.5654]

SVI: 100%|██████████| 25/25 [00:00<00:00,  1.10it/s, loss=2375.8054]