# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianNeuralNetwork, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[-0.84902284  0.73533697  0.11449077  0.27326443 -0.85327431]
 [-0.68876913  0.507391   -0.26447278  0.33487447 -0.60533834]
 [-0.45558024  0.72171067 -0.76540726  0.81322327  0.64394703]
 [ 0.40792383  0.44783707 -0.67687233  0.35037202 -0.05752822]
 [ 0.78812978  0.33303642 -0.91643312 -0.34801155 -0.88680455]
 [ 0.49107852 -0.71513548  0.24090308  0.17019137 -0.31519956]
 [-0.48444562  0.84287714  0.11720863  0.15438249 -0.63520841]
 [-0.97482046 -0.29286474 -0.76114254 -0.19698918 -0.16855604]
 [-0.98761174 -0.92192165  0.93769083  0.53491842 -0.34187264]
 [-0.06489629  0.07786136 -0.26758214 -0.40542587  0.26388793]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a1', 'a2', 'a1', 'a1', 'a1', 'a1', 'a1', 'a1', 'a2', 'a2']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [1, 0, 0, 0, 0, 1, 0, 1, 0, 1]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/25 [00:00<?, ?it/s]

SVI:   4%|▍         | 1/25 [00:01<00:24,  1.04s/it]

SVI:   4%|▍         | 1/25 [00:01<00:24,  1.04s/it, loss=768.6033]

SVI:   8%|▊         | 2/25 [00:01<00:23,  1.04s/it, loss=830.1647]

SVI:  12%|█▏        | 3/25 [00:01<00:22,  1.04s/it, loss=828.9351]

SVI:  16%|█▌        | 4/25 [00:01<00:21,  1.04s/it, loss=739.5614]

SVI:  20%|██        | 5/25 [00:01<00:20,  1.04s/it, loss=771.6803]

SVI:  24%|██▍       | 6/25 [00:01<00:19,  1.04s/it, loss=692.5308]

SVI:  28%|██▊       | 7/25 [00:01<00:18,  1.04s/it, loss=664.1085]

SVI:  32%|███▏      | 8/25 [00:01<00:17,  1.04s/it, loss=761.7911]

SVI:  36%|███▌      | 9/25 [00:01<00:16,  1.04s/it, loss=661.9954]

SVI:  40%|████      | 10/25 [00:01<00:15,  1.04s/it, loss=743.9520]

SVI:  44%|████▍     | 11/25 [00:01<00:14,  1.04s/it, loss=713.7764]

SVI:  48%|████▊     | 12/25 [00:01<00:13,  1.04s/it, loss=716.4031]

SVI:  52%|█████▏    | 13/25 [00:01<00:12,  1.04s/it, loss=690.1927]

SVI:  56%|█████▌    | 14/25 [00:01<00:11,  1.04s/it, loss=669.4858]

SVI:  60%|██████    | 15/25 [00:01<00:10,  1.04s/it, loss=634.6261]

SVI:  64%|██████▍   | 16/25 [00:01<00:09,  1.04s/it, loss=644.8038]

SVI:  68%|██████▊   | 17/25 [00:01<00:08,  1.04s/it, loss=646.9639]

SVI:  72%|███████▏  | 18/25 [00:01<00:07,  1.04s/it, loss=621.8231]

SVI:  76%|███████▌  | 19/25 [00:01<00:06,  1.04s/it, loss=651.2640]

SVI:  80%|████████  | 20/25 [00:01<00:05,  1.04s/it, loss=594.0844]

SVI:  84%|████████▍ | 21/25 [00:01<00:04,  1.04s/it, loss=606.5217]

SVI:  88%|████████▊ | 22/25 [00:01<00:03,  1.04s/it, loss=605.5956]

SVI:  92%|█████████▏| 23/25 [00:01<00:02,  1.04s/it, loss=584.6168]

SVI:  96%|█████████▌| 24/25 [00:01<00:01,  1.04s/it, loss=588.7834]

SVI: 100%|██████████| 25/25 [00:01<00:00,  1.04s/it, loss=558.7612]

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:00<00:29,  1.13it/s]

SVI:   3%|▎         | 1/34 [00:00<00:29,  1.13it/s, loss=491.4809]

SVI:   6%|▌         | 2/34 [00:00<00:28,  1.13it/s, loss=437.1353]

SVI:   9%|▉         | 3/34 [00:00<00:27,  1.13it/s, loss=456.8987]

SVI:  12%|█▏        | 4/34 [00:00<00:26,  1.13it/s, loss=479.4700]

SVI:  15%|█▍        | 5/34 [00:00<00:25,  1.13it/s, loss=436.7328]

SVI:  18%|█▊        | 6/34 [00:00<00:24,  1.13it/s, loss=429.1130]

SVI:  21%|██        | 7/34 [00:00<00:23,  1.13it/s, loss=473.4406]

SVI:  24%|██▎       | 8/34 [00:00<00:22,  1.13it/s, loss=433.9196]

SVI:  26%|██▋       | 9/34 [00:00<00:22,  1.13it/s, loss=421.4324]

SVI:  29%|██▉       | 10/34 [00:00<00:21,  1.13it/s, loss=424.1578]

SVI:  32%|███▏      | 11/34 [00:00<00:20,  1.13it/s, loss=433.7170]

SVI:  35%|███▌      | 12/34 [00:00<00:19,  1.13it/s, loss=420.6451]

SVI:  38%|███▊      | 13/34 [00:00<00:18,  1.13it/s, loss=420.7078]

SVI:  41%|████      | 14/34 [00:00<00:17,  1.13it/s, loss=414.4806]

SVI:  44%|████▍     | 15/34 [00:00<00:16,  1.13it/s, loss=396.6289]

SVI:  47%|████▋     | 16/34 [00:00<00:15,  1.13it/s, loss=392.7285]

SVI:  50%|█████     | 17/34 [00:00<00:15,  1.13it/s, loss=430.5060]

SVI:  53%|█████▎    | 18/34 [00:00<00:14,  1.13it/s, loss=403.5169]

SVI:  56%|█████▌    | 19/34 [00:00<00:13,  1.13it/s, loss=427.3660]

SVI:  59%|█████▉    | 20/34 [00:00<00:12,  1.13it/s, loss=413.3443]

SVI:  62%|██████▏   | 21/34 [00:00<00:11,  1.13it/s, loss=395.3856]

SVI:  65%|██████▍   | 22/34 [00:00<00:10,  1.13it/s, loss=405.2549]

SVI:  68%|██████▊   | 23/34 [00:00<00:09,  1.13it/s, loss=386.7797]

SVI:  71%|███████   | 24/34 [00:00<00:08,  1.13it/s, loss=406.0678]

SVI:  74%|███████▎  | 25/34 [00:00<00:07,  1.13it/s, loss=391.3121]

SVI:  76%|███████▋  | 26/34 [00:00<00:07,  1.13it/s, loss=397.0534]

SVI:  79%|███████▉  | 27/34 [00:00<00:06,  1.13it/s, loss=379.1143]

SVI:  82%|████████▏ | 28/34 [00:00<00:05,  1.13it/s, loss=383.8476]

SVI:  85%|████████▌ | 29/34 [00:00<00:04,  1.13it/s, loss=389.7839]

SVI:  88%|████████▊ | 30/34 [00:00<00:03,  1.13it/s, loss=380.8804]

SVI:  91%|█████████ | 31/34 [00:00<00:02,  1.13it/s, loss=373.8156]

SVI:  94%|█████████▍| 32/34 [00:00<00:01,  1.13it/s, loss=377.6057]

SVI:  97%|█████████▋| 33/34 [00:00<00:00,  1.13it/s, loss=375.2412]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.99it/s, loss=375.2412]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.99it/s, loss=395.3547]