# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianNeuralNetwork, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[ 0.36702465 -0.84918891 -0.13612599 -0.57146028  0.58567354]
 [-0.44483146  0.05183434 -0.48589003 -0.75788452 -0.21380554]
 [ 0.66064628 -0.91794058 -0.6573124  -0.95100795  0.5011209 ]
 [ 0.07706762 -0.20392151  0.39099552  0.71061918  0.62945817]
 [ 0.20215294 -0.00224427  0.76079564  0.83099187  0.80722402]
 [ 0.28666522 -0.81237201  0.82866257 -0.91628203 -0.07988366]
 [-0.20035062 -0.35099085 -0.10003091  0.35504183  0.47720833]
 [-0.89492622 -0.8547006   0.80475207 -0.65341102  0.99016116]
 [-0.6996793   0.93844659 -0.30279567 -0.68352908 -0.65784717]
 [-0.26939649  0.99824961 -0.87126126  0.86352375  0.04643973]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a2', 'a1', 'a2', 'a1', 'a1', 'a2', 'a2', 'a1', 'a2', 'a1']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [1, 1, 1, 1, 0, 1, 1, 0, 1, 0]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:01<00:33,  1.03s/it]

SVI:   3%|▎         | 1/34 [00:01<00:33,  1.03s/it, loss=2754.8665]

SVI:   6%|▌         | 2/34 [00:01<00:32,  1.03s/it, loss=3647.8027]

SVI:   9%|▉         | 3/34 [00:01<00:31,  1.03s/it, loss=3020.5388]

SVI:  12%|█▏        | 4/34 [00:01<00:30,  1.03s/it, loss=2508.5710]

SVI:  15%|█▍        | 5/34 [00:01<00:29,  1.03s/it, loss=3670.0417]

SVI:  18%|█▊        | 6/34 [00:01<00:28,  1.03s/it, loss=2028.4708]

SVI:  21%|██        | 7/34 [00:01<00:27,  1.03s/it, loss=2539.7537]

SVI:  24%|██▎       | 8/34 [00:01<00:26,  1.03s/it, loss=2453.6775]

SVI:  26%|██▋       | 9/34 [00:01<00:25,  1.03s/it, loss=2742.7898]

SVI:  29%|██▉       | 10/34 [00:01<00:24,  1.03s/it, loss=2456.8000]

SVI:  32%|███▏      | 11/34 [00:01<00:23,  1.03s/it, loss=2320.8049]

SVI:  35%|███▌      | 12/34 [00:01<00:22,  1.03s/it, loss=2148.5962]

SVI:  38%|███▊      | 13/34 [00:01<00:21,  1.03s/it, loss=2590.6721]

SVI:  41%|████      | 14/34 [00:01<00:20,  1.03s/it, loss=2138.0107]

SVI:  44%|████▍     | 15/34 [00:01<00:19,  1.03s/it, loss=2283.2844]

SVI:  47%|████▋     | 16/34 [00:01<00:18,  1.03s/it, loss=3110.3201]

SVI:  50%|█████     | 17/34 [00:01<00:17,  1.03s/it, loss=3133.1953]

SVI:  53%|█████▎    | 18/34 [00:01<00:16,  1.03s/it, loss=2489.0786]

SVI:  56%|█████▌    | 19/34 [00:01<00:15,  1.03s/it, loss=2740.7686]

SVI:  59%|█████▉    | 20/34 [00:01<00:14,  1.03s/it, loss=2649.9011]

SVI:  62%|██████▏   | 21/34 [00:01<00:13,  1.03s/it, loss=1854.9042]

SVI:  65%|██████▍   | 22/34 [00:01<00:12,  1.03s/it, loss=1871.9208]

SVI:  68%|██████▊   | 23/34 [00:01<00:11,  1.03s/it, loss=3099.6719]

SVI:  71%|███████   | 24/34 [00:01<00:10,  1.03s/it, loss=2567.0759]

SVI:  74%|███████▎  | 25/34 [00:01<00:09,  1.03s/it, loss=3193.3008]

SVI:  76%|███████▋  | 26/34 [00:01<00:08,  1.03s/it, loss=2607.0398]

SVI:  79%|███████▉  | 27/34 [00:01<00:07,  1.03s/it, loss=3144.4590]

SVI:  82%|████████▏ | 28/34 [00:01<00:06,  1.03s/it, loss=2985.1736]

SVI:  85%|████████▌ | 29/34 [00:01<00:05,  1.03s/it, loss=2559.7031]

SVI:  88%|████████▊ | 30/34 [00:01<00:04,  1.03s/it, loss=1768.7998]

SVI:  91%|█████████ | 31/34 [00:01<00:03,  1.03s/it, loss=2064.0999]

SVI:  94%|█████████▍| 32/34 [00:01<00:02,  1.03s/it, loss=2674.5598]

SVI:  97%|█████████▋| 33/34 [00:01<00:01,  1.03s/it, loss=2166.9089]

SVI: 100%|██████████| 34/34 [00:01<00:00, 21.37it/s, loss=2166.9089]

SVI: 100%|██████████| 34/34 [00:01<00:00, 21.37it/s, loss=1717.0033]

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:00<00:28,  1.16it/s]

SVI:   3%|▎         | 1/34 [00:00<00:28,  1.16it/s, loss=3814.0361]

SVI:   6%|▌         | 2/34 [00:00<00:27,  1.16it/s, loss=2213.4788]

SVI:   9%|▉         | 3/34 [00:00<00:26,  1.16it/s, loss=2647.6072]

SVI:  12%|█▏        | 4/34 [00:00<00:25,  1.16it/s, loss=1668.2158]

SVI:  15%|█▍        | 5/34 [00:00<00:24,  1.16it/s, loss=2612.1370]

SVI:  18%|█▊        | 6/34 [00:00<00:24,  1.16it/s, loss=1554.7114]

SVI:  21%|██        | 7/34 [00:00<00:23,  1.16it/s, loss=2194.6143]

SVI:  24%|██▎       | 8/34 [00:00<00:22,  1.16it/s, loss=1984.1578]

SVI:  26%|██▋       | 9/34 [00:00<00:21,  1.16it/s, loss=2481.2742]

SVI:  29%|██▉       | 10/34 [00:00<00:20,  1.16it/s, loss=2602.0916]

SVI:  32%|███▏      | 11/34 [00:00<00:19,  1.16it/s, loss=2209.8132]

SVI:  35%|███▌      | 12/34 [00:00<00:18,  1.16it/s, loss=1633.6660]

SVI:  38%|███▊      | 13/34 [00:00<00:18,  1.16it/s, loss=2814.0896]

SVI:  41%|████      | 14/34 [00:00<00:17,  1.16it/s, loss=3231.7646]

SVI:  44%|████▍     | 15/34 [00:00<00:16,  1.16it/s, loss=2506.9397]

SVI:  47%|████▋     | 16/34 [00:00<00:15,  1.16it/s, loss=2549.2483]

SVI:  50%|█████     | 17/34 [00:00<00:14,  1.16it/s, loss=2329.8630]

SVI:  53%|█████▎    | 18/34 [00:00<00:13,  1.16it/s, loss=2812.5361]

SVI:  56%|█████▌    | 19/34 [00:00<00:12,  1.16it/s, loss=2633.5510]

SVI:  59%|█████▉    | 20/34 [00:00<00:12,  1.16it/s, loss=1991.3070]

SVI:  62%|██████▏   | 21/34 [00:00<00:11,  1.16it/s, loss=2021.6045]

SVI:  65%|██████▍   | 22/34 [00:00<00:10,  1.16it/s, loss=2105.1648]

SVI:  68%|██████▊   | 23/34 [00:00<00:09,  1.16it/s, loss=2717.5344]

SVI:  71%|███████   | 24/34 [00:00<00:08,  1.16it/s, loss=1698.5459]

SVI:  74%|███████▎  | 25/34 [00:00<00:07,  1.16it/s, loss=2155.8918]

SVI:  76%|███████▋  | 26/34 [00:00<00:06,  1.16it/s, loss=1886.5228]

SVI:  79%|███████▉  | 27/34 [00:00<00:06,  1.16it/s, loss=2302.5935]

SVI:  82%|████████▏ | 28/34 [00:00<00:05,  1.16it/s, loss=2069.6421]

SVI:  85%|████████▌ | 29/34 [00:00<00:04,  1.16it/s, loss=3036.7549]

SVI:  88%|████████▊ | 30/34 [00:00<00:03,  1.16it/s, loss=2428.3362]

SVI:  91%|█████████ | 31/34 [00:00<00:02,  1.16it/s, loss=2100.3125]

SVI:  94%|█████████▍| 32/34 [00:00<00:01,  1.16it/s, loss=2595.5723]

SVI:  97%|█████████▋| 33/34 [00:00<00:00,  1.16it/s, loss=2679.7854]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.96it/s, loss=2679.7854]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.96it/s, loss=2009.9371]