# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianNeuralNetwork, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[ 0.64783107 -0.1200202   0.75586219 -0.86934957 -0.90455361]
 [-0.54532368  0.56583307 -0.58126058 -0.13721458  0.97908053]
 [-0.64810657  0.110884    0.17312524 -0.43261185 -0.92646936]
 [-0.24078839 -0.81056417 -0.65332185 -0.75103946  0.45486477]
 [ 0.37332728 -0.75486257  0.79234769 -0.66954572 -0.53082414]
 [ 0.35004975 -0.63932496 -0.52700487 -0.25303934 -0.03365811]
 [ 0.31528771 -0.25823404 -0.92720287  0.7615285   0.11012865]
 [ 0.37452903  0.01560845  0.28657609  0.90803531 -0.2570207 ]
 [-0.16684198 -0.25403719  0.63964558  0.77825925  0.32368817]
 [ 0.58181631 -0.36313562 -0.21609753  0.15489762  0.34558745]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a1', 'a1', 'a1', 'a2', 'a2', 'a1', 'a2', 'a1', 'a2', 'a2']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [1, 0, 1, 1, 1, 0, 0, 1, 1, 0]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:01<00:35,  1.09s/it]

SVI:   3%|▎         | 1/34 [00:01<00:35,  1.09s/it, loss=2532.3059]

SVI:   6%|▌         | 2/34 [00:01<00:34,  1.09s/it, loss=2219.6877]

SVI:   9%|▉         | 3/34 [00:01<00:33,  1.09s/it, loss=2075.9622]

SVI:  12%|█▏        | 4/34 [00:01<00:32,  1.09s/it, loss=2280.8491]

SVI:  15%|█▍        | 5/34 [00:01<00:31,  1.09s/it, loss=2036.1293]

SVI:  18%|█▊        | 6/34 [00:01<00:30,  1.09s/it, loss=2473.6741]

SVI:  21%|██        | 7/34 [00:01<00:29,  1.09s/it, loss=2259.0862]

SVI:  24%|██▎       | 8/34 [00:01<00:28,  1.09s/it, loss=3367.7451]

SVI:  26%|██▋       | 9/34 [00:01<00:27,  1.09s/it, loss=1983.2770]

SVI:  29%|██▉       | 10/34 [00:01<00:26,  1.09s/it, loss=2599.7458]

SVI:  32%|███▏      | 11/34 [00:01<00:24,  1.09s/it, loss=2839.4482]

SVI:  35%|███▌      | 12/34 [00:01<00:23,  1.09s/it, loss=2139.4363]

SVI:  38%|███▊      | 13/34 [00:01<00:22,  1.09s/it, loss=2772.0520]

SVI:  41%|████      | 14/34 [00:01<00:21,  1.09s/it, loss=2530.0310]

SVI:  44%|████▍     | 15/34 [00:01<00:20,  1.09s/it, loss=2909.7571]

SVI:  47%|████▋     | 16/34 [00:01<00:19,  1.09s/it, loss=2399.4463]

SVI:  50%|█████     | 17/34 [00:01<00:18,  1.09s/it, loss=2184.5830]

SVI:  53%|█████▎    | 18/34 [00:01<00:17,  1.09s/it, loss=2492.9241]

SVI:  56%|█████▌    | 19/34 [00:01<00:16,  1.09s/it, loss=3209.3467]

SVI:  59%|█████▉    | 20/34 [00:01<00:15,  1.09s/it, loss=3301.2844]

SVI:  62%|██████▏   | 21/34 [00:01<00:14,  1.09s/it, loss=2557.5869]

SVI:  65%|██████▍   | 22/34 [00:01<00:13,  1.09s/it, loss=2732.5029]

SVI:  68%|██████▊   | 23/34 [00:01<00:11,  1.09s/it, loss=3392.7161]

SVI:  71%|███████   | 24/34 [00:01<00:10,  1.09s/it, loss=2138.9778]

SVI:  74%|███████▎  | 25/34 [00:01<00:09,  1.09s/it, loss=2528.4192]

SVI:  76%|███████▋  | 26/34 [00:01<00:08,  1.09s/it, loss=3474.6768]

SVI:  79%|███████▉  | 27/34 [00:01<00:07,  1.09s/it, loss=2239.4395]

SVI:  82%|████████▏ | 28/34 [00:01<00:06,  1.09s/it, loss=3670.6562]

SVI:  85%|████████▌ | 29/34 [00:01<00:05,  1.09s/it, loss=2370.5393]

SVI:  88%|████████▊ | 30/34 [00:01<00:04,  1.09s/it, loss=2501.3792]

SVI:  91%|█████████ | 31/34 [00:01<00:03,  1.09s/it, loss=3264.2864]

SVI:  94%|█████████▍| 32/34 [00:01<00:02,  1.09s/it, loss=2149.6716]

SVI:  97%|█████████▋| 33/34 [00:01<00:01,  1.09s/it, loss=2431.8572]

SVI: 100%|██████████| 34/34 [00:01<00:00, 20.44it/s, loss=2431.8572]

SVI: 100%|██████████| 34/34 [00:01<00:00, 20.44it/s, loss=3138.4597]

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:00<00:30,  1.10it/s]

SVI:   3%|▎         | 1/34 [00:00<00:30,  1.10it/s, loss=3235.2725]

SVI:   6%|▌         | 2/34 [00:00<00:29,  1.10it/s, loss=2174.3894]

SVI:   9%|▉         | 3/34 [00:00<00:28,  1.10it/s, loss=2594.6809]

SVI:  12%|█▏        | 4/34 [00:00<00:27,  1.10it/s, loss=2388.4182]

SVI:  15%|█▍        | 5/34 [00:00<00:26,  1.10it/s, loss=2161.4294]

SVI:  18%|█▊        | 6/34 [00:00<00:25,  1.10it/s, loss=3688.1067]

SVI:  21%|██        | 7/34 [00:00<00:24,  1.10it/s, loss=3297.4001]

SVI:  24%|██▎       | 8/34 [00:00<00:23,  1.10it/s, loss=2060.2556]

SVI:  26%|██▋       | 9/34 [00:00<00:22,  1.10it/s, loss=2728.9778]

SVI:  29%|██▉       | 10/34 [00:00<00:21,  1.10it/s, loss=3423.9971]

SVI:  32%|███▏      | 11/34 [00:00<00:20,  1.10it/s, loss=2188.2842]

SVI:  35%|███▌      | 12/34 [00:00<00:20,  1.10it/s, loss=1517.4860]

SVI:  38%|███▊      | 13/34 [00:00<00:19,  1.10it/s, loss=3364.2429]

SVI:  41%|████      | 14/34 [00:00<00:18,  1.10it/s, loss=2693.3469]

SVI:  44%|████▍     | 15/34 [00:00<00:17,  1.10it/s, loss=2563.6387]

SVI:  47%|████▋     | 16/34 [00:00<00:16,  1.10it/s, loss=2881.7800]

SVI:  50%|█████     | 17/34 [00:00<00:15,  1.10it/s, loss=3009.9167]

SVI:  53%|█████▎    | 18/34 [00:00<00:14,  1.10it/s, loss=3521.0115]

SVI:  56%|█████▌    | 19/34 [00:00<00:13,  1.10it/s, loss=3165.5100]

SVI:  59%|█████▉    | 20/34 [00:00<00:12,  1.10it/s, loss=2369.6672]

SVI:  62%|██████▏   | 21/34 [00:00<00:11,  1.10it/s, loss=3148.9434]

SVI:  65%|██████▍   | 22/34 [00:00<00:10,  1.10it/s, loss=2727.6091]

SVI:  68%|██████▊   | 23/34 [00:00<00:10,  1.10it/s, loss=2234.0505]

SVI:  71%|███████   | 24/34 [00:00<00:09,  1.10it/s, loss=1988.7587]

SVI:  74%|███████▎  | 25/34 [00:00<00:08,  1.10it/s, loss=2419.4175]

SVI:  76%|███████▋  | 26/34 [00:00<00:07,  1.10it/s, loss=1969.5557]

SVI:  79%|███████▉  | 27/34 [00:00<00:06,  1.10it/s, loss=2863.5527]

SVI:  82%|████████▏ | 28/34 [00:00<00:05,  1.10it/s, loss=2301.5518]

SVI:  85%|████████▌ | 29/34 [00:00<00:04,  1.10it/s, loss=2805.4863]

SVI:  88%|████████▊ | 30/34 [00:00<00:03,  1.10it/s, loss=2145.1572]

SVI:  91%|█████████ | 31/34 [00:00<00:02,  1.10it/s, loss=3408.4844]

SVI:  94%|█████████▍| 32/34 [00:00<00:01,  1.10it/s, loss=2622.4355]

SVI:  97%|█████████▋| 33/34 [00:00<00:00,  1.10it/s, loss=2620.2600]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.26it/s, loss=2620.2600]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.26it/s, loss=2086.6143]