# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianNeuralNetwork, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[-0.02473283  0.50751075 -0.78263065  0.09815859  0.102233  ]
 [ 0.40475325  0.77955205  0.1212864  -0.91129346  0.19444372]
 [ 0.99419362  0.14759915  0.45713084  0.99108701  0.11133062]
 [-0.02476026  0.52546496 -0.53805732 -0.191273   -0.70612836]
 [-0.59528387  0.96643909 -0.66917334 -0.00210478 -0.45880682]
 [-0.82501651 -0.48377565 -0.3695304   0.54225873 -0.82794632]
 [-0.03033812  0.53219985 -0.76061668 -0.65421336 -0.08215649]
 [ 0.12005198 -0.83744266 -0.43291859  0.89464088  0.24062601]
 [ 0.19745327 -0.9023426   0.43745001  0.47973743  0.14720159]
 [ 0.14166436 -0.7859547  -0.57887188 -0.23518317  0.22287756]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianNeuralNetwork(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a2', 'a1', 'a1', 'a1', 'a2', 'a2', 'a1', 'a1', 'a1', 'a1']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [0, 0, 0, 0, 0, 0, 1, 1, 0, 0]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:01<00:35,  1.07s/it]

SVI:   3%|▎         | 1/34 [00:01<00:35,  1.07s/it, loss=2745.6965]

SVI:   6%|▌         | 2/34 [00:01<00:34,  1.07s/it, loss=2986.3738]

SVI:   9%|▉         | 3/34 [00:01<00:33,  1.07s/it, loss=2387.4102]

SVI:  12%|█▏        | 4/34 [00:01<00:32,  1.07s/it, loss=2541.7307]

SVI:  15%|█▍        | 5/34 [00:01<00:30,  1.07s/it, loss=2113.9326]

SVI:  18%|█▊        | 6/34 [00:01<00:29,  1.07s/it, loss=2417.6892]

SVI:  21%|██        | 7/34 [00:01<00:28,  1.07s/it, loss=1862.7701]

SVI:  24%|██▎       | 8/34 [00:01<00:27,  1.07s/it, loss=2018.6683]

SVI:  26%|██▋       | 9/34 [00:01<00:26,  1.07s/it, loss=2582.2622]

SVI:  29%|██▉       | 10/34 [00:01<00:25,  1.07s/it, loss=3111.8489]

SVI:  32%|███▏      | 11/34 [00:01<00:24,  1.07s/it, loss=1604.9305]

SVI:  35%|███▌      | 12/34 [00:01<00:23,  1.07s/it, loss=2273.9570]

SVI:  38%|███▊      | 13/34 [00:01<00:22,  1.07s/it, loss=2428.6528]

SVI:  41%|████      | 14/34 [00:01<00:21,  1.07s/it, loss=2497.3848]

SVI:  44%|████▍     | 15/34 [00:01<00:20,  1.07s/it, loss=2217.8850]

SVI:  47%|████▋     | 16/34 [00:01<00:19,  1.07s/it, loss=2896.3328]

SVI:  50%|█████     | 17/34 [00:01<00:18,  1.07s/it, loss=2144.2297]

SVI:  53%|█████▎    | 18/34 [00:01<00:17,  1.07s/it, loss=2565.9626]

SVI:  56%|█████▌    | 19/34 [00:01<00:16,  1.07s/it, loss=2073.4744]

SVI:  59%|█████▉    | 20/34 [00:01<00:14,  1.07s/it, loss=2857.8076]

SVI:  62%|██████▏   | 21/34 [00:01<00:13,  1.07s/it, loss=2553.8301]

SVI:  65%|██████▍   | 22/34 [00:01<00:12,  1.07s/it, loss=2175.6475]

SVI:  68%|██████▊   | 23/34 [00:01<00:11,  1.07s/it, loss=2713.9778]

SVI:  71%|███████   | 24/34 [00:01<00:10,  1.07s/it, loss=2448.9033]

SVI:  74%|███████▎  | 25/34 [00:01<00:09,  1.07s/it, loss=2766.2354]

SVI:  76%|███████▋  | 26/34 [00:01<00:08,  1.07s/it, loss=2248.3601]

SVI:  79%|███████▉  | 27/34 [00:01<00:07,  1.07s/it, loss=2739.6111]

SVI:  82%|████████▏ | 28/34 [00:01<00:06,  1.07s/it, loss=2589.9817]

SVI:  85%|████████▌ | 29/34 [00:01<00:05,  1.07s/it, loss=2358.7751]

SVI:  88%|████████▊ | 30/34 [00:01<00:04,  1.07s/it, loss=2249.0181]

SVI:  91%|█████████ | 31/34 [00:01<00:03,  1.07s/it, loss=2197.8467]

SVI:  94%|█████████▍| 32/34 [00:01<00:02,  1.07s/it, loss=3129.8047]

SVI:  97%|█████████▋| 33/34 [00:01<00:01,  1.07s/it, loss=1995.3867]

SVI: 100%|██████████| 34/34 [00:01<00:00, 20.98it/s, loss=1995.3867]

SVI: 100%|██████████| 34/34 [00:01<00:00, 20.98it/s, loss=2145.6897]

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:00<00:28,  1.15it/s]

SVI:   3%|▎         | 1/34 [00:00<00:28,  1.15it/s, loss=2345.1296]

SVI:   6%|▌         | 2/34 [00:00<00:27,  1.15it/s, loss=2670.8440]

SVI:   9%|▉         | 3/34 [00:00<00:26,  1.15it/s, loss=2265.0725]

SVI:  12%|█▏        | 4/34 [00:00<00:26,  1.15it/s, loss=3141.4094]

SVI:  15%|█▍        | 5/34 [00:00<00:25,  1.15it/s, loss=2990.9961]

SVI:  18%|█▊        | 6/34 [00:00<00:24,  1.15it/s, loss=2165.7390]

SVI:  21%|██        | 7/34 [00:00<00:23,  1.15it/s, loss=2763.4971]

SVI:  24%|██▎       | 8/34 [00:00<00:22,  1.15it/s, loss=2348.8225]

SVI:  26%|██▋       | 9/34 [00:00<00:21,  1.15it/s, loss=2112.3713]

SVI:  29%|██▉       | 10/34 [00:00<00:20,  1.15it/s, loss=1670.9781]

SVI:  32%|███▏      | 11/34 [00:00<00:20,  1.15it/s, loss=3234.7883]

SVI:  35%|███▌      | 12/34 [00:00<00:19,  1.15it/s, loss=2286.3445]

SVI:  38%|███▊      | 13/34 [00:00<00:18,  1.15it/s, loss=2716.9460]

SVI:  41%|████      | 14/34 [00:00<00:17,  1.15it/s, loss=2096.4707]

SVI:  44%|████▍     | 15/34 [00:00<00:16,  1.15it/s, loss=1782.2344]

SVI:  47%|████▋     | 16/34 [00:00<00:15,  1.15it/s, loss=2248.6350]

SVI:  50%|█████     | 17/34 [00:00<00:14,  1.15it/s, loss=2661.7957]

SVI:  53%|█████▎    | 18/34 [00:00<00:13,  1.15it/s, loss=2552.1394]

SVI:  56%|█████▌    | 19/34 [00:00<00:13,  1.15it/s, loss=2332.3108]

SVI:  59%|█████▉    | 20/34 [00:00<00:12,  1.15it/s, loss=1782.0928]

SVI:  62%|██████▏   | 21/34 [00:00<00:11,  1.15it/s, loss=3127.6375]

SVI:  65%|██████▍   | 22/34 [00:00<00:10,  1.15it/s, loss=3103.4990]

SVI:  68%|██████▊   | 23/34 [00:00<00:09,  1.15it/s, loss=2900.5508]

SVI:  71%|███████   | 24/34 [00:00<00:08,  1.15it/s, loss=2321.7625]

SVI:  74%|███████▎  | 25/34 [00:00<00:07,  1.15it/s, loss=2308.8884]

SVI:  76%|███████▋  | 26/34 [00:00<00:06,  1.15it/s, loss=2259.8606]

SVI:  79%|███████▉  | 27/34 [00:00<00:06,  1.15it/s, loss=2477.0994]

SVI:  82%|████████▏ | 28/34 [00:00<00:05,  1.15it/s, loss=2236.4563]

SVI:  85%|████████▌ | 29/34 [00:00<00:04,  1.15it/s, loss=2784.7712]

SVI:  88%|████████▊ | 30/34 [00:00<00:03,  1.15it/s, loss=2992.0222]

SVI:  91%|█████████ | 31/34 [00:00<00:02,  1.15it/s, loss=2531.3137]

SVI:  94%|█████████▍| 32/34 [00:00<00:01,  1.15it/s, loss=1498.1771]

SVI:  97%|█████████▋| 33/34 [00:00<00:00,  1.15it/s, loss=1810.2936]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.55it/s, loss=1810.2936]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.55it/s, loss=1185.8979]