# Contextual Multi-Armed Bandit

For the contextual multi-armed bandit (cMAB) when user information is available (context), we implemented a generalisation of Thompson sampling algorithm ([Agrawal and Goyal, 2014](https://arxiv.org/pdf/1209.3352.pdf)) based on NumPyro.

![title](img/cmab.png)

The following notebook contains an example of usage of the class Cmab, which implements the algorithm above.

In [1]:
import numpy as np

from pybandits.cmab import CmabBernoulli
from pybandits.model import BayesianLogisticRegression, BnnLayerParams, BnnParams, FeaturesConfig, StudentTArray

/home/runner/.cache/pypoetry/virtualenvs/pybandits-vYJB-miV-py3.10/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [2]:
n_samples = 1000
n_features = 5

First, we need to define the input context matrix $X$ of size ($n\_samples, n\_features$) and the mapping of possible actions $a_i \in A$ to their associated model.

In [3]:
# context
X = 2 * np.random.random_sample((n_samples, n_features)) - 1  # random float in the interval (-1, 1)
print("X: context matrix of shape (n_samples, n_features)")
print(X[:10])

X: context matrix of shape (n_samples, n_features)
[[ 0.38518708 -0.80188884  0.75037336  0.30109345 -0.93193865]
 [ 0.89262087 -0.82559488  0.17489083  0.16192051  0.18243383]
 [ 0.45447373  0.44208391  0.33917671  0.73181135 -0.92222607]
 [ 0.25650311 -0.51499052 -0.61833323 -0.35362391  0.88035678]
 [ 0.34377215 -0.53313562  0.54480927  0.82437485  0.73241441]
 [-0.19520624 -0.89808462 -0.34068961  0.43272596  0.69985211]
 [-0.68742952  0.64603739 -0.5406911   0.12269711  0.17190558]
 [-0.31872498 -0.67458442 -0.05386499  0.66263795 -0.59662955]
 [-0.31026912 -0.09703329 -0.88330978  0.9943011  -0.40101305]
 [-0.67347741  0.32206931  0.94620081  0.59363865 -0.04499232]]


In [4]:
# define action model
bias = StudentTArray.cold_start(mu=1, sigma=2, shape=1)
weight = StudentTArray.cold_start(shape=(n_features, 1))
layer_params = BnnLayerParams(weight=weight, bias=bias)
model_params = BnnParams(bnn_layer_params=[layer_params])
feature_config = FeaturesConfig(n_features=n_features)

update_method = "VI"
update_kwargs = {"num_steps": 100, "batch_size": 128, "optimizer_type": "adam"}

actions = {
    "a1": BayesianLogisticRegression(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
    "a2": BayesianLogisticRegression(
        model_params=model_params,
        feature_config=feature_config,
        update_method=update_method,
        update_kwargs=update_kwargs,
    ),
}

We can now init the bandit given the mapping of actions $a_i$ to their model.

In [5]:
# init contextual Multi-Armed Bandit model
cmab = CmabBernoulli(actions=actions)

The predict function below returns the action selected by the bandit at time $t$: $a_t = argmax_k P(r=1|\beta_k, x_t)$. The bandit selects one action per each sample of the contect matrix $X$.

In [6]:
# predict action
pred_actions, _, _ = cmab.predict(X)
print("Recommended action: {}".format(pred_actions[:10]))

Recommended action: ['a2', 'a2', 'a1', 'a2', 'a1', 'a1', 'a2', 'a1', 'a1', 'a1']


Now, we observe the rewards and the context from the environment. In this example rewards and the context are randomly simulated.

In [7]:
# simulate reward from environment
simulated_rewards = np.random.randint(2, size=n_samples).tolist()
print("Simulated rewards: {}".format(simulated_rewards[:10]))

Simulated rewards: [1, 0, 0, 1, 0, 0, 0, 0, 0, 1]


Finally, we update the model providing per each action sample: (i) its context $x_t$ (ii) the action $a_t$ selected by the bandit, (iii) the corresponding reward $r_t$.

In [8]:
# update model
cmab.update(context=X, actions=pred_actions, rewards=simulated_rewards)

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:01<00:34,  1.04s/it]

SVI:   3%|▎         | 1/34 [00:01<00:34,  1.04s/it, loss=761.1512]

SVI:   6%|▌         | 2/34 [00:01<00:33,  1.04s/it, loss=586.2944]

SVI:   9%|▉         | 3/34 [00:01<00:32,  1.04s/it, loss=669.8809]

SVI:  12%|█▏        | 4/34 [00:01<00:31,  1.04s/it, loss=732.0130]

SVI:  15%|█▍        | 5/34 [00:01<00:30,  1.04s/it, loss=756.5780]

SVI:  18%|█▊        | 6/34 [00:01<00:29,  1.04s/it, loss=764.6536]

SVI:  21%|██        | 7/34 [00:01<00:27,  1.04s/it, loss=733.8990]

SVI:  24%|██▎       | 8/34 [00:01<00:26,  1.04s/it, loss=722.8975]

SVI:  26%|██▋       | 9/34 [00:01<00:25,  1.04s/it, loss=755.7281]

SVI:  29%|██▉       | 10/34 [00:01<00:24,  1.04s/it, loss=616.8581]

SVI:  32%|███▏      | 11/34 [00:01<00:23,  1.04s/it, loss=637.0118]

SVI:  35%|███▌      | 12/34 [00:01<00:22,  1.04s/it, loss=774.9716]

SVI:  38%|███▊      | 13/34 [00:01<00:21,  1.04s/it, loss=538.1444]

SVI:  41%|████      | 14/34 [00:01<00:20,  1.04s/it, loss=724.3806]

SVI:  44%|████▍     | 15/34 [00:01<00:19,  1.04s/it, loss=676.9940]

SVI:  47%|████▋     | 16/34 [00:01<00:18,  1.04s/it, loss=592.6953]

SVI:  50%|█████     | 17/34 [00:01<00:17,  1.04s/it, loss=632.4276]

SVI:  53%|█████▎    | 18/34 [00:01<00:16,  1.04s/it, loss=631.0948]

SVI:  56%|█████▌    | 19/34 [00:01<00:15,  1.04s/it, loss=597.6461]

SVI:  59%|█████▉    | 20/34 [00:01<00:14,  1.04s/it, loss=577.4164]

SVI:  62%|██████▏   | 21/34 [00:01<00:13,  1.04s/it, loss=625.0996]

SVI:  65%|██████▍   | 22/34 [00:01<00:12,  1.04s/it, loss=595.7969]

SVI:  68%|██████▊   | 23/34 [00:01<00:11,  1.04s/it, loss=527.0017]

SVI:  71%|███████   | 24/34 [00:01<00:10,  1.04s/it, loss=626.0307]

SVI:  74%|███████▎  | 25/34 [00:01<00:09,  1.04s/it, loss=563.0215]

SVI:  76%|███████▋  | 26/34 [00:01<00:08,  1.04s/it, loss=611.9253]

SVI:  79%|███████▉  | 27/34 [00:01<00:07,  1.04s/it, loss=624.9019]

SVI:  82%|████████▏ | 28/34 [00:01<00:06,  1.04s/it, loss=632.6047]

SVI:  85%|████████▌ | 29/34 [00:01<00:05,  1.04s/it, loss=586.5856]

SVI:  88%|████████▊ | 30/34 [00:01<00:04,  1.04s/it, loss=500.8680]

SVI:  91%|█████████ | 31/34 [00:01<00:03,  1.04s/it, loss=625.4227]

SVI:  94%|█████████▍| 32/34 [00:01<00:02,  1.04s/it, loss=583.6212]

SVI:  97%|█████████▋| 33/34 [00:01<00:01,  1.04s/it, loss=582.5718]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.30it/s, loss=582.5718]

SVI: 100%|██████████| 34/34 [00:01<00:00, 22.30it/s, loss=551.8984]

SVI:   0%|          | 0/34 [00:00<?, ?it/s]

SVI:   3%|▎         | 1/34 [00:00<00:28,  1.15it/s]

SVI:   3%|▎         | 1/34 [00:00<00:28,  1.15it/s, loss=485.7837]

SVI:   6%|▌         | 2/34 [00:00<00:27,  1.15it/s, loss=524.3901]

SVI:   9%|▉         | 3/34 [00:00<00:27,  1.15it/s, loss=503.5366]

SVI:  12%|█▏        | 4/34 [00:00<00:26,  1.15it/s, loss=514.2759]

SVI:  15%|█▍        | 5/34 [00:00<00:25,  1.15it/s, loss=558.3243]

SVI:  18%|█▊        | 6/34 [00:00<00:24,  1.15it/s, loss=509.1866]

SVI:  21%|██        | 7/34 [00:00<00:23,  1.15it/s, loss=533.1298]

SVI:  24%|██▎       | 8/34 [00:00<00:22,  1.15it/s, loss=539.2700]

SVI:  26%|██▋       | 9/34 [00:00<00:21,  1.15it/s, loss=459.4896]

SVI:  29%|██▉       | 10/34 [00:00<00:20,  1.15it/s, loss=497.3948]

SVI:  32%|███▏      | 11/34 [00:00<00:20,  1.15it/s, loss=493.0543]

SVI:  35%|███▌      | 12/34 [00:00<00:19,  1.15it/s, loss=478.9595]

SVI:  38%|███▊      | 13/34 [00:00<00:18,  1.15it/s, loss=475.6686]

SVI:  41%|████      | 14/34 [00:00<00:17,  1.15it/s, loss=466.5169]

SVI:  44%|████▍     | 15/34 [00:00<00:16,  1.15it/s, loss=466.4682]

SVI:  47%|████▋     | 16/34 [00:00<00:15,  1.15it/s, loss=497.7782]

SVI:  50%|█████     | 17/34 [00:00<00:14,  1.15it/s, loss=523.5311]

SVI:  53%|█████▎    | 18/34 [00:00<00:13,  1.15it/s, loss=491.7693]

SVI:  56%|█████▌    | 19/34 [00:00<00:13,  1.15it/s, loss=476.5991]

SVI:  59%|█████▉    | 20/34 [00:00<00:12,  1.15it/s, loss=452.3814]

SVI:  62%|██████▏   | 21/34 [00:00<00:11,  1.15it/s, loss=442.5337]

SVI:  65%|██████▍   | 22/34 [00:00<00:10,  1.15it/s, loss=484.4587]

SVI:  68%|██████▊   | 23/34 [00:00<00:09,  1.15it/s, loss=466.1553]

SVI:  71%|███████   | 24/34 [00:00<00:08,  1.15it/s, loss=433.7575]

SVI:  74%|███████▎  | 25/34 [00:00<00:07,  1.15it/s, loss=464.6805]

SVI:  76%|███████▋  | 26/34 [00:00<00:06,  1.15it/s, loss=494.1927]

SVI:  79%|███████▉  | 27/34 [00:00<00:06,  1.15it/s, loss=447.1537]

SVI:  82%|████████▏ | 28/34 [00:00<00:05,  1.15it/s, loss=441.4069]

SVI:  85%|████████▌ | 29/34 [00:00<00:04,  1.15it/s, loss=456.9338]

SVI:  88%|████████▊ | 30/34 [00:00<00:03,  1.15it/s, loss=442.1207]

SVI:  91%|█████████ | 31/34 [00:00<00:02,  1.15it/s, loss=419.3470]

SVI:  94%|█████████▍| 32/34 [00:00<00:01,  1.15it/s, loss=411.3867]

SVI:  97%|█████████▋| 33/34 [00:00<00:00,  1.15it/s, loss=447.1209]

SVI: 100%|██████████| 34/34 [00:01<00:00, 23.75it/s, loss=447.1209]

SVI: 100%|██████████| 34/34 [00:01<00:00, 23.75it/s, loss=423.9324]